### ISSUE TITLE
Umlaute are not shown correctly

### ISSUE THREAD

**Issue by Lucurus** [openhab/openhab-distro#411] opened 2017-01-30 19:06 UTC
Umlaute (äöü) are not displayed correctly on the webapp. Instead of the letter, _Ã¤_ (i.e. NetzwerkgerÃ¤t) is displayed.

**Comment by Lucurus** [comment] 2017-01-30 20:30
I'm not entirely sure to which distro to post this, so if this is incorrect, please delete it.

**Comment by kaikreuzer** [comment] 2017-01-30 21:51
Looks like a duplicate of https://github.com/openhab/openhab-distro/issues/409, which is a duplicate of https://github.com/openhab/openhab2-addons/issues/1750

**Closed by kaikreuzer** 2017-01-30 21:51 UTC

**Comment by Lucurus** [comment] 2017-01-30 21:52
Thanks. Sorry, I should have checked.
