### ISSUE TITLE
Loader constraint violation when using sendMail action with attachment

### ISSUE THREAD

**Issue by mhilbush** [openhab/openhab-distro#838] opened 2019-01-06 03:04 UTC
I'm seeing this error when calling the sendMail action with an attachment. The error doesn't occur when calling the sendMail action without an attachment.
```
019-01-05 20:21:47.282 [ERROR] [ntime.internal.engine.RuleEngineImpl] - Rule 
'TestRuleOn': loader constraint violation: when resolving method
 "javax.mail.BodyPart.setDataHandler(Ljavax/activation/DataHandler;)V" the class 
loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) of the 
current class, org/apache/commons/mail/MultiPartEmail, and the class 
loader (instance of org/eclipse/osgi/internal/loader/EquinoxClassLoader) for 
the method's defining class, javax/mail/Part, have different Class objects for the 
type javax/activation/DataHandler used in the signature
```
I'm seeing this on snapshot build 1484 (also 1489). I'm seeing the error on two separate systems. When I restore an earlier build (in this case 1458), the error doesn't occur. 

The sendMail call in my rule is this
```
sendMail("my@email.address", "Email subject", "Email body", "file:///path/to/image.jpg")
```
or this
```
sendMail("my@email.address", "Email subject", "Email body", "http://my.host/path/to/image.jpg")
```

It didn't look like anything had changed with the sendMail action in the openhab1 repo (hence the reason for not opening the issue in that repo).

**Comment by wborn** [comment] 2019-01-12 09:42
Maybe @ffang has some suggestions for fixing it?

**Comment by kaikreuzer** [comment] 2019-01-12 13:38
@ffang The manifest of the bundle can be found here: https://github.com/openhab/openhab1-addons/blob/master/bundles/action/org.openhab.action.mail/META-INF/MANIFEST.MF

It currently indeed does not have an import-package statement for `javax.activation`, but when analysing it, I also added this to my test bundle and it unfortunately didn't make any difference.

I agree with you that the boot delegation is supposed to be a last resort only and that resolution should happen against OSGi bundles first - so I am not quite sure, why it still wasn't working with such an import...

**Comment by kaikreuzer** [comment] 2019-01-12 13:59
I've created https://github.com/openhab/openhab1-addons/pull/5767 in any case as this should be there. Maybe my tests weren't correct and this will fix it after all - let's try a distro after this has been merged.

**Comment by kaikreuzer** [comment] 2019-01-12 14:03
Argh, stupid me. I should have read my earlier comment, where I already said that this bundle correctly resolves the dependency against the org.apache.servicemix.specs.activation-api bundle - so adding the import definitely won't fix anything...

The problem is probably rather somewhere in the rule engine, which does not know about that package and still needs to resolve some classes in order to execute the action. Not sure where to look for this, though...

**Comment by maggu2810** [comment] 2019-01-15 20:10
Do you still need `osgi.compatibility.bootdelegation = true` at all?

**Comment by kaikreuzer** [comment] 2019-01-16 07:54
From what I remember: YES, very much so! At least as long as we have openHAB 1 compatibility as those add-ons have many issues and many of them broke without the boot delegation.

**Comment by mhilbush** [comment] 2019-01-16 13:53
@kaikreuzer I just retested this on build 1502. Your change [here](https://github.com/openhab/openhab1-addons/pull/5767) seems to have fixed the issue for me.

**Comment by yveshanoulle** [comment] 2019-01-16 17:40
@mhilbush I assume this means i can install the lastest version and it's fixed?

**Comment by mhilbush** [comment] 2019-01-16 18:35
@yveshanoulle Yes, it is working again for me after installing the latest snapshot.

**Comment by kaikreuzer** [comment] 2019-01-16 21:40
Indeed, for me as well!
So https://github.com/openhab/openhab1-addons/pull/5767 indeed fixed it, pfew.

**Closed by kaikreuzer** 2019-01-16 21:40 UTC
Labels: bug

**Comment by yveshanoulle** [comment] 2019-01-17 19:57
Also on my side this works.
