### ISSUE TITLE
openHAB 2.5 initial dashboard stops if openhab2-addons is installed

### ISSUE THREAD

**Issue by bwosborne2** [openhab/openhab-distro#1031] opened 2019-12-28 00:25 UTC
openHAB 2.5 initial dashboard stops if openhab2-addons is installed in a fresh installation 
From my testing, it appears this broke sometime between Milestone 1 and Milestone 2.
I tested this with apt packages and manual installs on a Raspberry Pi 3B+. 

Removing the addons & OH and then reinstalling OH appears to allow OH to run. In my quick testing I was able to upgrade from M1 to M2 to M3 and still have OH work so this appears to be a fresh installation issue.

We have had several users run into this issue recently. The openhab log just shows the dashboard stopping either before or after LSP starts. OH keeps running but Jetty gives a 404 error for /start/index.

**Comment by kaikreuzer** [comment] 2019-12-30 08:37
I would assume that this is likely to be a duplicate of https://github.com/openhab/openhab-distro/issues/1031. Planning to have a closer look at it soon.

**Comment by kaikreuzer** [comment] 2019-12-30 16:15
Closing as a duplicate of https://github.com/openhab/openhab-distro/issues/961.

I hope the workaround explained in https://github.com/openhab/openhab-distro/issues/961#issuecomment-569721834 is acceptible for existing 2.5 users.

**Comment by bwosborne2** [comment] 2019-12-30 16:28
It is only acceptable if the Linux Installation and the Download pages are updated with the workaround. When this was discovered as broken months ago the pages should have at least been updated to warn users of breakage.

**Comment by kaikreuzer** [comment] 2020-01-01 20:41
The de-installation is not directly related to https://github.com/openhab/openhab-distro/issues/961, so I re-open it as it isn't really an exact duplicate, just closely related.

I have created https://github.com/openhab/openhab-webui/pull/163, which fixes this issue, once 2.5.1 add-ons are released.

**Comment by kaikreuzer** [comment] 2020-01-03 14:11
Fixed with #1041.

**Closed by kaikreuzer** 2020-01-03 14:11 UTC

**Comment by bwosborne2** [comment] 2020-01-03 14:28
Does this mean there may be a mew snapshot or milestone?

**Comment by kaikreuzer** [comment] 2020-01-03 14:32
Even a release. See https://github.com/openhab/openhab-distro/issues/961#issuecomment-570090499 and https://community.openhab.org/t/development-of-openhab-3-0-0-and-2-5-x/89376.
