### ISSUE TITLE
Contact-Groups not updated

### ISSUE THREAD

**Issue by javayankee** [openhab/openhab-distro#482] opened 2017-07-13 11:58 UTC
Ich have several contacts in a group; some others in a group that itself is member of a group:

```java
Group ERD_Fenster   "Fenster unten [MAP(degroups.map):%s]"  <contact>   

Group FensterKU     "Fenster Küche [MAP(def.map):%s]"       <contact>   (ERD_Fenster)
Group FensterEZ     "Fenster Essecke [MAP(def.map):%s]"     <contact>   (ERD_Fenster)
Group FensterWZ     "Fenste/r Wohnzimmer [MAP(def.map):%s]"      <contact>   (ERD_Fenster)

Contact rweGaestebadFenster        "Fenster Gästebad [MAP(de.map):%s]" <contact>       (ERD_Fenster)    {rwe="id=b825f798-d162-41cb-9fc9-5ccef2f1306b,param=contact"}

Contact rweKuechenFensterL        "Küchenfenster links [MAP(de.map):%s]"    <contact>       (FensterKU,Contacts)        {rwe="id=0f49f2b4-65cd-4d45-8b32-e4ca7baeffb0,param=contact"}
Contact rweKuechenFensterR        "Küchenfenster rechts [MAP(de.map):%s]"    <contact>       (FensterKU,Contacts)       {rwe="id=b1ba5717-83e3-4962-ac6d-911cff30ca33,param=contact"}

Contact rweEsseckenFensterL        "Esseckenfenster links [MAP(de.map):%s]"  <contact>       (FensterEZ,Contacts) {rwe="id=e39660ba-acc8-4659-8ce0-44d4107d5d38,param=contact"}
Contact rweEsseckenFensterR        "Esseckenfenster rechts [MAP(de.map):%s]"  <contact>       (FensterEZ,Contacts) {rwe="id=cba20237-7601-46f5-a424-9e25bc4a7f50,param=contact"}

Contact rweWohnzimmerFensterL        "Wohnzimmerfenster links [MAP(de.map):%s]"       <contact>       (FensterWZ,Contacts) {rwe="id=5aca2a1e-7465-4264-8af3-b00e3ba9d5c0,param=contact"}
Contact rweWohnzimmerFensterR        "Wohnzimmerfenster rechts [MAP(de.map):%s]"       <contact>       (FensterWZ,Contacts) {rwe="id=1d6e8a47-0f92-4b8f-b9f4-280fc972e043,param=contact"}
```

In Version 2.0, Group state changed to "CLOSED" as soon as the last windows inside that group has been closed, or to "OPEN" when all windows where openend. 

Since 2.1 this isn't working any longer which causes some rules not to work.

**Comment by ThomDietrich** [comment] 2017-07-13 13:54
Hello @javayankee,
please use the openHAB community forum for usage or troubleshooting questions. The Issue Tracker is reserved for confirmed bugs and enhancement discussions.
You might have missed: https://github.com/openhab/openhab-distro/wiki/openHAB-2.1-Release-Notes#breaking-changes-that-require-manual-interaction-after-the-upgrade
Also check out the already updated documentation on the matter: http://docs.openhab.org/configuration/items.html#group-types

I'll go ahead and close the issue but please let us know if the issue is solved for you and if the documentation article was helpful in the matter. Best!

**Closed by ThomDietrich** 2017-07-13 13:54 UTC

**Comment by javayankee** [comment] 2017-07-15 17:05
Thanks ThomDietrich, indeed I missed the necessary changes in the group types. Thanks for giving me the hint on this. Best!
