### ISSUE TITLE
No webui's

### ISSUE THREAD

**Issue by martinvw** [openhab/openhab-distro#879] opened 2019-02-20 20:15 UTC
Is it expected that webui's which have been split of recently cannot be installed anymore in the snapshots?

CC: @davidgraeff

**Comment by wborn** [comment] 2019-02-20 21:15
I also ran into this issue today. Testing a fix now. :-)

**Comment by lucacalcaterra** [comment] 2019-02-21 13:15
I'm working on a binding development, today i create a fresh copy of the environment but launching openhab runtime hangs to please stand by while ui are being installed.

Is this the issue ? But i didn't understand how to fix it..

Antoher Issue is that Eclipse , when launch the distro give me the followin errors:

![image](https://user-images.githubusercontent.com/879825/53171495-28ceca80-35e3-11e9-99db-e4c959396f1e.png)

**Comment by wborn** [comment] 2019-02-21 15:20
Looks like a different issue @lucacalcaterra.

**Comment by davidgraeff** [comment] 2019-02-21 15:26
@lucacalcaterra I do had the same issue though a few days ago (on Linux, so it's not a Windows only problem)

**Comment by kaikreuzer** [comment] 2019-02-21 20:54
Please note that we didn't yet have a successful web-ui build at all, so all our latest PRs to that repo (and its feature definition) are not yet available to the distro...

I guess we first have to fix that one here: https://ci.openhab.org/job/openHAB-WebUI/10/console

**Comment by wborn** [comment] 2019-02-21 20:57
> I guess we first have to fix that one here

I could reproduce it by wiping my local repo. But fixing it is another thing. :wink:

**Comment by martinvw** [comment] 2019-02-21 21:01
> Please note that we didn't yet have a successful web-ui build at all, so all our latest PRs to that repo (and its feature definition) are not yet available to the distro...

I missed that, let me take a look as well in parallel :-)

**Comment by wborn** [comment] 2019-02-21 21:55
It mostly looks like Tycho has problems resolving the BND build dashboard @kaikreuzer. 
What do you think would be the best way to solve it? 

Build the dashboard using Tycho again? 
Using BND for all webui bundles? It wouldn't allow for the openhab2-addons parent.
Maybe you know of something else?

**Comment by maggu2810** [comment] 2019-02-21 22:02
That's related:
https://github.com/openhab/openhab-core/issues/590#issuecomment-465626360

**Comment by kaikreuzer** [comment] 2019-02-21 22:03
I really wonder why that can matter? It is in the same reactor and there's a pom dependency to it defined. I would expect that there's no difference in how the referenced artifact is built as long as it is built by the reactor...

**Comment by martinvw** [comment] 2019-02-21 22:35
I have a partial local build re-enabling tycho (I was not patient enough and my build env is not in a good shape)

If you are interested I pushed the branch:

https://github.com/openhab/openhab-webui/pull/13

**Comment by wborn** [comment] 2019-02-21 22:54
Thanks @martinvw!

Maybe the [Tycho Wiki entry](https://wiki.eclipse.org/Tycho/How_Tos/Dependency_on_pom-first_artifacts#It_is_not_possible_to_mix_pom-first_and_manifest-first_projects_in_the_same_reactor_build.) about not being able to mix POM-fist and manifest-first projects in the same reactor explains this issue?

After reading it I tried the following which also worked:

* Removing `org.openhab.ui.dashboard` from the reactor
* Adding dependencies on `org.openhab.ui.dashboard` (similar to basicui) in:
  - org.openhab.ui.classic
  - org.openhab.ui.homebuilder
  - org.openhab.ui.paper
  - org.openhab.ui.restdocs
* Build `org.openhab.ui.dashboard`
* Build the whole reactor (no longer including `org.openhab.ui.dashboard`)

**Comment by martinvw** [comment] 2019-02-21 22:56
> After reading it I tried the following which also worked:

If that makes more sense and is closer to the way forward I would prefer that, mine is more like a step backward :-)

**Comment by maggu2810** [comment] 2019-02-22 06:15
Wouldn't it be much simpler to migrate the other UIs to a non-tycho build?
It shouldn't a big deal.
I already migrated the basic, classic and the Paper UI before it gets removed.
There where just minor additional steps to be done (e.g. moving snippets to `src/main/resources` etc.).

**Comment by martinvw** [comment] 2019-02-22 07:18
@maggu2810 I agree 😊

I don’t expect that I can make time today but if I can I will mention it here before starting

**Comment by kaikreuzer** [comment] 2019-02-22 07:24
> Wouldn't it be much simpler to migrate the other UIs to a non-tycho build?

For a quick fix (which we need to get back to a working snapshot distro), it is even much simpler to just merge https://github.com/openhab/openhab-webui/pull/13 - this reduces the time pressure for moving everything to a non-tycho build.

**Comment by maggu2810** [comment] 2019-02-22 07:52
> I don’t expect that I can make time today but if I can I will mention it here before starting

If you need some support or assistance to move things forward, feel free to ping me.

**Comment by martinvw** [comment] 2019-02-22 10:40
@maggu2810 I started a WIP PR, I believe that I did it alright :-)

**Comment by martinvw** [comment] 2019-02-22 10:57
@maggu2810 if you would know by heart what I need to get this dependency in the correct way:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project org.openhab.ui.classic: Compilation failure
[ERROR] D:\Documents\_Martin\Java\openhab-webui\org.openhab.ui.classic\src\main\java\org\openhab\ui\classic\internal\render\PageRenderer.java: The type org.eclipse.emf.common.util.EList cannot be resolved. It is indirectly referenced from required .class files

**Comment by maggu2810** [comment] 2019-02-22 10:59
Add this:

```xml
<dependency>
  <groupId>org.openhab.core.bom</groupId>
  <artifactId>org.openhab.core.bom.compile-model</artifactId>
  <type>pom</type>
</dependency>
```

**Comment by martinvw** [comment] 2019-02-22 11:01
@maggu2810 it works, with:

```

    <dependency>
      <groupId>org.openhab.core.bundles</groupId>
      <artifactId>org.openhab.core.model.core</artifactId>
      <version>${project.version}</version>
    </dependency>
```

**Comment by martinvw** [comment] 2019-02-22 11:19
@maggu2810 what should I do with lib folders? Replace with the real maven dependency?

**Comment by maggu2810** [comment] 2019-02-22 11:25
IMHO

* If there are artifacts that are already OSGi bundles: use Maven dependencies and adapt the features to rely on that, too
* If there are artifacts but they are not OSGi bundles: use Maven dependencies and bnd instructions (Conditional / Private Package) to include the content.

**Comment by wborn** [comment] 2019-02-22 12:00
Did any of you also try build 1530? It should contain the webui artifacts of the successful build. But it doesn't show any UI at all on a new installation. :neutral_face:

**Comment by martinvw** [comment] 2019-02-22 12:26
Indeed same here :-(

**Comment by martinvw** [comment] 2019-02-22 12:32
@wborn I could now manually install the feature: 'openhab-ui-dashboard'

**Comment by martinvw** [comment] 2019-02-22 12:55
After the manual install, only these problems remain:

> 2019-02-22 13:43:59.376 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-misc-lsp, openhab-misc-dropbox1, openhab-binding-yahooweather, openhab-misc-restdocs'

**Comment by kaikreuzer** [comment] 2019-02-22 12:58
> @wborn I could now manually install the feature: 'openhab-ui-dashboard'
> After the rest did come, so maybe its something small now, any ideas?

I'd say we should add a feature dependency to the dashboard to all the single UIs in https://github.com/openhab/openhab-webui/blob/master/features/src/main/feature/feature.xml. Wdyt?

**Comment by kaikreuzer** [comment] 2019-02-22 12:58
> openhab-binding-yahooweather

Better remove this from your setup as it does not exist anymore...

> openhab-misc-restdocs

This is now called `openhab-ui-restdocs`.

**Comment by wborn** [comment] 2019-02-22 12:59
There also needs to be a dependency so you can use the dashboard to select the installation package on initial installation.

**Comment by kaikreuzer** [comment] 2019-02-22 13:02
You're right, that's the tricky one - it used to be part of openhab-runtime-base, but as it is not part of openhab-core, it cannot be in the base feature anymore.

**Comment by wborn** [comment] 2019-02-22 13:47
How about adding the openhab-ui-dashboard to featuresBoot in [org.apache.karaf.features.cfg](https://github.com/openhab/openhab-distro/blob/7ecb1d3e547d57460a6688f1ad5ac5b4c9a5a20c/distributions/openhab/src/main/filtered-resources/userdata/etc/org.apache.karaf.features.cfg#L32-L49)?

**Comment by kaikreuzer** [comment] 2019-02-22 13:48
Might work, can you give it a try?

**Comment by martinvw** [comment] 2019-02-22 14:11
> Better remove this from your setup as it does not exist anymore...

I feel a little bit stupid but how do I do that? feature:uninstall does not suffice?

**Comment by kaikreuzer** [comment] 2019-02-22 14:15
Uninstall it through Paper UI or (if you have configured it in addons.cfg) remove it from addons.cfg. That should do the job.

**Comment by wborn** [comment] 2019-02-22 14:15
> can you give it a try?

It works on a local build so I've created #883. :smile:

**Closed** 2019-02-22 14:18 UTC

**Comment by martinvw** [comment] 2019-02-22 14:21
> Uninstall it through Paper UI or (if you have configured it in addons.cfg) remove it from addons.cfg. That should do the job.

But I can't see it in the PaperUI because it does not exists anymore :-)

**Comment by wborn** [comment] 2019-02-22 14:23
You can remove it from `userdata/config/org/openhab/addons.config`

**Comment by martinvw** [comment] 2019-02-22 15:15
> You can remove it from `userdata/config/org/openhab/addons.config`

Yes that worked!

**Comment by kaikreuzer** [comment] 2019-02-22 17:43
https://ci.openhab.org/job/openHAB-WebUI/14/console fails as it picks up an openhab.core bundle that was built this afternoon (and which has DS requirements enabled). I assume this comes from a local Maven repo on Jenkins, which would be an incorrect configuration (will try to change it).

But @maggu2810: This seems to tell me that https://github.com/openhab/openhab-core/pull/595 will break this and we will need to adapt all our Tycho builds - so please let us test/prepare this before merging https://github.com/openhab/openhab-core/pull/595.

**Comment by maggu2810** [comment] 2019-02-22 20:59
First someone should fix the Jenkins configuration that merge request builders jobs does not pollute the Maven repositories used by other jobs.

IIRC you did not use the current master's HEAD but the latest "snapshot release" (don't know how you tell it) in the p2 repositories. Correct?

If it is correct, I assume we can move other things foward and fix that stuff parallel. Didn't we?

I written it already somewhere else:
I am not able to build the webui repository at all.
IMHO it should be able to clone a repository containing Maven projects and enter `mvn clean install`.
Perhaps this could be fixed, too. Then I could perhaps also have a look at and try to help.

**Comment by kaikreuzer** [comment] 2019-02-22 21:03
> First someone should fix the Jenkins configuration

I did that immediately after my message above.

> IIRC you did not use the current master's HEAD but the latest "snapshot release" (don't know how you tell it) in the p2 repositories. Correct?

How are p2 repos related here? The build should not at all depend on anything in a p2 repo.

> I am not able to build the webui repository at all.

Even with the latest master? Why? @wborn worked hard on making it all build, even on a clean local Maven repo.

**Comment by maggu2810** [comment] 2019-02-22 21:05
> Even with the latest master? Why? @wborn worked hard on making it all build, even on a clean local Maven repo.

I checked out the current master minutes before.
The message is the same as the last one.

```
$ mvn clean install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.openhab.ui:pom:[unknown-version]: Could not find artifact org.openhab:pom-addons2:pom:2.5.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 5, column 11
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.openhab.ui:pom:[unknown-version] (/home/maggu2810/data/shared/bin/pkgs/eclipse/oh.git/openhab-webui/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.openhab.ui:pom:[unknown-version]: Could not find artifact org.openhab:pom-addons2:pom:2.5.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 5, column 11 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

> How are p2 repos related here? The build should not at all depend on anything in a p2 repo.

Perhaps things has been changed.
If your Tycho build does not consume the openHAB Core bundles from the p2 target platform why did we create a p2 repo in openHAB Core at all?

**Comment by kaikreuzer** [comment] 2019-02-22 21:07
You are right, Jenkins has the same problem:
```
19:39:10 [FATAL] Non-resolvable parent POM: Could not find artifact org.openhab:pom-addons2:pom:2.5.0-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 5, column 11
```

> why did we create a p2 repo in openHAB Core at all?

Because that's how those bundles are made available in the target platform of the Addons IDE setup. That's there only use, they are not relevant for Maven at all.

**Comment by maggu2810** [comment] 2019-02-22 21:08
You have to build the addons repository first to get a copy of that POM in the local repository...

**Comment by kaikreuzer** [comment] 2019-02-22 21:11
So there are probably two solutions:
1. Make the build use the parent pom defined in openhab-core (and which is also used by openhab2-addons)
2. Add the artifactory snapshot repo to the pom (assuming that addons is always built before webui).

Probably 1 is the preferred option.

**Comment by maggu2810** [comment] 2019-02-22 21:28
org.eclipse.equinox.event

* 1.3.100.v20140115-1647: misses the provide capability header
* 1.4.0.v20170105-1446 (and I am pretty sure every above): contains the provide capability header

I will give it a try, but I am in good spirits to bump the p2 repo from Oxygen to Photon (in the pom-tycho pom) will already solve the problem.

**Comment by maggu2810** [comment] 2019-02-22 22:59
@kaikreuzer I added some PRs to hopefully improve the overall situation.

**Comment by wborn** [comment] 2019-02-23 15:34
I've updated some POMs in https://github.com/openhab/openhab-webui/pull/21 which creates a working webui build for me with an empty Maven repo @kaikreuzer.

There's also some storage/permission issue on Jenkins causing all builds to fail currently.

**Comment by lucacalcaterra** [comment] 2019-02-26 09:18
> @lucacalcaterra I do had the same issue though a few days ago (on Linux, so it's not a Windows only problem)
At the and, on my windows pc can't start ui,while on linux yes.  How can fix it for develop my binding ? I'm very confused, perhaps don't know so much the openhab architecture (and java related stack). I tried to point to latest 2.5m1 but nothing (while some days ago i did)

**Comment by lucacalcaterra** [comment] 2019-02-26 09:19
ps  the ide setup for development on o.h. site is still valid ?
