### ISSUE TITLE
Multiple Time cron expressions in rule not working

### ISSUE THREAD

**Issue by dschulte** [openhab/openhab-distro#355] opened 2016-12-17 01:02 UTC
Same issue was present in openHAB 1.x: https://github.com/openhab/openhab/issues/2524

Works (fires every five seconds):
```
rule "cron test"
when
	// Time cron "0 0 0 * * ?" or
	Time cron "0/5 * * * * ?"
then
	logInfo("cron", "test")
end
```

Doesn't work as expected (second cron doesn't fire):
```
rule "cron test"
when
	Time cron "0 0 0 * * ?" or
	Time cron "0/5 * * * * ?"
then
	logInfo("cron", "test")
end
```

I'm using the current apt version:
```
openhab2-offline/testing,now 2.0.0~b4 all  [installiert]
  openHAB Offline Distribution
```

**Comment by BlinkyBillToo** [comment] 2016-12-18 15:37
I have the same issue; any Time cron statement that is below another Time cron statement in a when or chain does not trigger.

I'm running OH2 "version":"0.9.0.201611102032"

**Comment by kaikreuzer** [comment] 2016-12-18 15:41
I can confirm the issue. Might I ask you to enter it at https://github.com/eclipse/smarthome/issues? Thanks!

**Comment by kaikreuzer** [comment] 2016-12-18 19:17
Thanks @dschulte!

**Comment by HAF-Blade** [comment] 2017-03-05 10:33
I've got the same issue here with multiple "time cron ... or" expressions.
They never work in my system.
When I split up the rule (so that there is only one single time cron expression) it works fine but this makes the rules really unreadable :(

**Comment by madattack** [comment] 2017-03-26 10:06
same for me

**Comment by kaikreuzer** [comment] 2017-05-24 13:10
Fixed by https://github.com/eclipse/smarthome/issues/3326

**Closed by kaikreuzer** 2017-05-24 13:10 UTC

**Comment by ThomDietrich** [comment] 2017-05-24 13:41
@kaikreuzer when will this be merged into openhab? I might have been a bit quick >.< https://community.openhab.org/t/multiple-cron-expressions/20930/9
Do I need to remove this message?

**Comment by kaikreuzer** [comment] 2017-05-24 13:46
I thought that at least you know [how to check it yourself](https://github.com/eclipse/smarthome/wiki/ESH-used-in-openHAB) 😛 
See https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes

> I might have been a bit quick

It is already in since April 29, so you were far too slow ;-)

**Comment by ThomDietrich** [comment] 2017-05-24 14:35
Know and check are two different things :D I saw that the PR was merged a while ago but how do I know which ESH is in the latest snapshot? I do not have an instance running and I can't find any info on this [here](https://openhab.ci.cloudbees.com/job/openHAB-Distribution). Please enlighten me :)

**Comment by kaikreuzer** [comment] 2017-05-24 14:38
> Please enlighten me :)

I thought I did :-) Ok, I will try again:

https://hudson.eclipse.org/smarthome/job/SmartHomeDistribution-Stable/changes shows that eclipse/smarthome#3326 is included in ESH stable since April 29 (and thus is part in ANY openHAB distro that was built after that date). [Here](https://openhab.ci.cloudbees.com/job/openHAB-Distribution) you can see that this is hence the case since at least build 906.

**Comment by ThomDietrich** [comment] 2017-05-24 14:48
> shows that eclipse/smarthome#3326 is included in ESH stable

check

> since April 29

check

> and thus is part in ANY openHAB distro that was built after that date

This is the missing piece, last time I checked this was a manual process. Correct?

> [Here](https://openhab.ci.cloudbees.com/job/openHAB-Distribution) you can see that this is hence the case since at least build 906.

You are pinpointing this on the date but shouldn't I be able to see this in the modules or build info somewhere under https://openhab.ci.cloudbees.com/job/openHAB-Distribution/906 ?

**Comment by BlinkyBillToo** [comment] 2017-05-24 16:32
Guys, thank you very much for your thoroughness and support.

m: +1 (646) 801-8254<tel:+16468018254>

-----Original Message-----
