### ISSUE TITLE
Valuecolor problems after update to OH2.2

### ISSUE THREAD

**Issue by iceman88** [openhab/openhab-distro#632] opened 2017-12-30 22:47 UTC
Since update Value Colors as described in the documentation insn't working anymore:
[https://docs.openhab.org/configuration/sitemaps.html#label-and-value-colors](https://docs.openhab.org/configuration/sitemaps.html#label-and-value-colors)

Sitemap:
`Text item=Update_WZ valuecolor=[>6000="red",>600="orange",<=600="green"]`

Rule:
```
`rule "LaCrosse2_Update"
when
    Item Temperature_WZ received update
then
    postUpdate(Update_WZ, new DateTimeType())
end`
```

See also:
[https://community.openhab.org/t/valuecolor-problems-after-update-to-oh2-2/37636]( https://community.openhab.org/t/valuecolor-problems-after-update-to-oh2-2/37636
)

**Comment by lolodomo** [comment] 2017-12-31 10:34
There is a big issue in the framework probably introduced with the DateTime refactory. It explains that valuecolor is no more working with DateTime.
I created the issue: https://github.com/eclipse/smarthome/issues/4828
And I have already proposed a fix.

**Comment by kaikreuzer** [comment] 2018-01-02 09:34
Thanks, closing as duplicate of https://github.com/eclipse/smarthome/issues/4828 then.

**Closed by kaikreuzer** 2018-01-02 09:34 UTC
