### ISSUE TITLE
Windows start  - running for first time in Windows  - Will not install KARAF

### ISSUE THREAD

**Issue by rcehon** [openhab/openhab-distro#148] opened 2016-02-26 15:53 UTC
Hi,
I am new at openHAB, but I thought I would check out the beta version of v2 since it looked pretty cool. I am running this on a Windows 10 machine and it looks like there is an installation issue with Karaf.

c:\OpenHab\OpenHab2.0>start.bat
Launching the openHAB runtime...
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
Unable to retrieve JAVA_HOME from Registry
JAVA_HOME is not valid: ""
The system cannot find the batch label specified - END
karaf.bat: JAVA_HOME not set; results may vary
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
ERROR: The system was unable to find the specified registry key or value.
karaf.bat: Unable to retrieve JAVA_HOME from Registry
karaf.bat: JAVA_HOME is not valid: ""

**Comment by dvanherbergen** [comment] 2016-02-26 15:58
Can you post the results of the following commands?
```
java -version
echo %JAVA_HOME%
```

**Comment by rcehon** [comment] 2016-02-26 16:05
c:\OpenHab\OpenHab2.0>java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) Client VM (build 25.73-b02, mixed mode, sharing)

c:\OpenHab\OpenHab2.0>echo %JAVA_HOME%
%JAVA_HOME%

**Comment by Nightshadow1258** [comment] 2016-04-08 16:40
i am getting the same error on start up

**Comment by adamcooks** [comment] 2016-04-16 22:51
Hi, I had this error too - after reading [this thread](https://community.openhab.org/t/oh2-karaf/5992) i installed the Java Developer Kit (JDK 8) and I was good to.

**Comment by kaikreuzer** [comment] 2016-04-17 07:57
Ok, so this seems to be a duplicate of https://github.com/openhab/openhab-distro/issues/56 - so I am closing it here.

**Closed by kaikreuzer** 2016-04-17 07:57 UTC
