### ISSUE TITLE
IllegalStateException: ServiceLocatorImpl has been shut down

### ISSUE THREAD

**Issue by HolgerHees** [openhab/openhab-distro#673] opened 2018-04-02 12:32 UTC
Currently I’m running openhab 2.1 without any problems.

But if I try to upgrade to openhab 2.2 or openhab 2.3 snapshot (1246) I get a lot of

```
2018-04-01 18:20:35.298 [WARN ] [org.eclipse.jetty.server.HttpChannel] - //mydomain.de/rest/sitemaps/_default/0201
javax.servlet.ServletException: javax.servlet.ServletException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_25,26,610229533) has been shut down
```

it is mostly if I use Habdroid. A lot of rest requests ( 1 of 10) are answered with a 500 or 503. In most of the cases Habdroid is requesting the same resource again so it works at the end. And it is not limited to the rest url in the exception. In most cases a request to my sitemap is failing but I think the reason is because the sitemap is the most request url.

I already saw some recommendations to disable logging for this classes but I think this can’t be the solution.

I opened this topic again because it happens now for a while without any improvements and i have not found any “working” solution… I searched a lot :-)

[exception.log](https://github.com/openhab/openhab-distro/files/1868059/exception.log)

[exception_debug.log](https://github.com/openhab/openhab-distro/files/1868058/exception_debug.log)

https://github.com/eclipse/smarthome/issues/5334

**Comment by kaikreuzer** [comment] 2018-04-02 15:55
Pretty sure this is a duplicate of https://github.com/openhab/openhab-core/issues/229.

**Closed by kaikreuzer** 2018-04-02 15:55 UTC
