### ISSUE TITLE
Add update.ps1 script functionality

### ISSUE THREAD

**Issue by BClark09** [openhab/openhab-distro#500] opened 2017-07-28 22:30 UTC
Following from #299

The windows script needs a few modifications to bring it up to the level of functionality that the Linux/Mac OS equivalent has:

 - It does not currently handle the update of addon files if old ones exist.
 - Ideally, the script should run it's own newer version from the downloaded archive. Otherwise, specific processes will always be one update too stale.

Additionally, the script is only compatible with PowerShell v5, this ought to be lowered to suit more installations. Ideally, as a `.bat` script instead of `.ps1`.

@ghys, @bdleedy any thoughts on this?

**Comment by ThomDietrich** [comment] 2017-07-31 08:58
I have no experience with PowerShell but judging from the information found here: https://en.wikipedia.org/wiki/PowerShell#PowerShell_4.0 Version 4 can be found on all Windows 7 and up PCs and would hence be acceptable. Going back to Batch is imho too much...

**Comment by BClark09** [comment] 2017-07-31 09:07
PowerShell 2 is found on all Windows 7 machines, although 4.0 can be downloaded and installed on any SP1 version, and it is fairly likely (but not certian) to have WMF 4.0 (which includes PS4.0) installed nowadays.

**Comment by ThomDietrich** [comment] 2017-07-31 09:17
![grafik](https://user-images.githubusercontent.com/2870104/28771115-df9ff158-75e1-11e7-8911-94eeacde2ce7.png)

Confirmed

**Comment by ghys** [comment] 2017-08-01 08:59
I'm reluctant about rewriting the current PowerShell script as a batch file too. we can expect PowerShell v2 to be installed on all Windows platforms.
Moreover, it would be a better fit to include it in https://github.com/openhab/openhab-docs/issues/447 which is PowerShell-based.

**Comment by bdleedy** [comment] 2017-08-05 21:26
Adding the 4.0 (or 2.0, do we seriously think that someone running openHAB WOULDN'T have their Windows machine updated??) requirement to the script would be good. I was going to suggest that. I haven't had time at all since the script was added. Next week the wife is out of town for business so I'll have all week to work on this. Since Windows 10 1703, shift-right click only produces an option to open PowerShell in the current location. It's becoming the defacto shell and is way easier and more powerful for this kind of application.

**Comment by bdleedy** [comment] 2017-08-05 22:49
Whoops, apparently Thom is one of those people.

**Comment by bdleedy** [comment] 2017-08-06 02:13
I'm starting to merge my updates into the script and also looking at what would need to be downgraded for PS2.0. It makes everything MUCH harder. I'm hoping that we can decide to go with 4.0.

**Comment by bdleedy** [comment] 2017-08-06 15:57
@ghys Is there a reason that you use a commandlet instead of just passing arguments to the script? Will this allow the script to be deleted and updated? It's one more (semi complicated) step for a user to understand.

**Comment by ghys** [comment] 2017-08-06 16:26
@bdleedy no real reason, just personal preference and habit - you can include a nice manpage-like documentation (i.e. `Get-Help Update-openHAB` or `man Update-openHAB`) for your cmdlet, also allows to add support for `-WhatIf` / `-Confirm` & friends with `[CmdletBinding(SupportsShouldProcess=$true)]`/ `$pscmdlet.ShouldProcess()` which AFAIK is only possible with cmdlets.
https://foxdeploy.com/2014/09/04/adding-whatif-support-to-your-scripts-the-right-way-and-how-you-shouldnt-do-it/
(true, I didn't take advantage of it here). To be honest a regular script would also be just fine.

**Comment by bdleedy** [comment] 2017-08-06 16:56
@ghys It makes no difference to me, I'm just trying to keep it simple for the users. I don't think it's too much to ask but it's definitely starting to push the boundary of the technical knowledge we should assume they have. I guess good documentation takes care of that though.

**Comment by bdleedy** [comment] 2017-08-06 17:04
Submitted pull request [509](https://github.com/openhab/openhab-distro/pull/509)

Fixes a few of the issues here. I BELIEVE that I have it suitable for PS 4.0 but I don't have a machine with that handy right now. (it's not possible to force a lower version except for 2.0) I think a script updater is all that's left.

@ghys Your script (besides the commandlet) was SO similar to mine except that you were handling the userdata way smarter than me and therefore didn't have the issues (and delays) I did. Great minds...

**Comment by bdleedy** [comment] 2017-12-13 15:52
Need tester for this.

**Comment by kaikreuzer** [comment] 2017-12-21 16:43
I guess we can close this here after #511 has been merged.

**Closed by kaikreuzer** 2017-12-21 16:43 UTC
