### ISSUE TITLE
Karaf : unresponsive console

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab-distro#244] opened 2016-07-01 15:01 UTC
Often the karaf console becomes very unresponsive, and the only way around that is to ssh into the runtime through a new session. 

Is anyone experiencing the same issue?

**Comment by kaikreuzer** [comment] 2016-07-01 15:49
No, never saw this.

Maybe you should better ask for help in the [Karaf forum](http://karaf.922171.n3.nabble.com/Karaf-User-f930749.html)? There should definitely be more experts around for such topics.

**Comment by maggu2810** [comment] 2016-07-01 18:46
> Is anyone experiencing the same issue?

I am using Karaf in a lot of my project and never seen that issue.
Does this also occur on the terminal console (not the ssh one).
Are you sure that the network connection is always up and no packages are lost (TCP statistic etc.)?

**Comment by xsnrg** [comment] 2016-07-01 18:55
I am experiencing it as well, in the latest snapshot.  Not even ctrl-c will do anything.  I have not experienced this before.  It still is receiving output from things running, but will accept no keyboard input.  I have it running in screen here, and am able to exit the screen session and re-enter it without issue.  I had responsiveness until it started in with some Sonos errors, but probably has nothing to do with it.  I will try to reproduce a few more times and see if a pattern is present.

**Comment by maggu2810** [comment] 2016-07-01 19:41
That is interesting.
The Karaf version has not been changed the last weeks / month, so it is perhaps related how a bundle consume resources of the OSGi framework. I don't know. Perhaps you could identify the problem using a debugger and look at the socket handling of Mina / SSHD.

**Comment by kgoderis** [comment] 2016-07-02 07:33
I now have the runtime running since last night in my ops env, and the console bit came to a halt. I can perfectly initiate the session as in:

```
2016-07-02 09:30:52.101 [INFO ] [he.sshd.server.session.ServerSession] - Server session created from /192.168.0.200:57921
2016-07-02 09:30:53.910 [INFO ] [server.session.ServerUserAuthService] - Session karaf@/192.168.0.200:57921 authenticated

```
but after that the terminal session hangs completely (e.g. I do not even arrive at the console prompt)

**Comment by kgoderis** [comment] 2016-07-02 15:21
I am not sure if this the right place to put the comment, but I have been profiling the runtime for a while with VisualVM. It seems that the "item"-QueueingThreadPoolExecutor is putting a burden on the system. Things are still working for the time being, but the 5 (+1 queue) threads in the QTPE are taking up 65% of the allocated bytes, and about 50% of the CPU time consumed by the JVM. It allocates around 25 MB of memory every second (based on the Sampler). However, when looking at the thread timeline, the  item-threads are only active 3-5% of the time.

**Comment by maggu2810** [comment] 2016-07-02 17:05
> but the 5 (+1 queue) threads in the QTPE are taking up 65% of the allocated bytes, and about 50% of the CPU time consumed by the JVM. It allocates around 25 MB of memory every second (based on the Sampler).

That sounds not so good and should be reported to ESH (IMHO).

**Comment by kaikreuzer** [comment] 2016-07-03 08:36
> It seems that the "item"-QueueingThreadPoolExecutor is putting a burden on the system. 

No, it is not the thread pool that is putting a burden to the system, but the jobs that it is executing. To analyze this, we would need a thread dump as mentioned in https://github.com/eclipse/smarthome/issues/1767#issuecomment-229884845.

Note that before the pool was introduced, all calls were done in a single thread, so we have now 5 times the capacity to before, so there should be no need to extend the pool size.

**Comment by kgoderis** [comment] 2016-07-03 08:40
I am actually trying to get one, but after a night on the Karaf runtime, the runtime as about 20K active threads now, the bulk being Timer-..... threads. 

On the Executor, the only place it is used right now is to notify Item listeners, no?

**Comment by kaikreuzer** [comment] 2016-07-03 08:55
>  the runtime as about 20K active threads now, the bulk being Timer-..... threads

This should like some bugs in your personal rules. Could you disable the ones where you create timers within a rule?

> On the Executor, the only place it is used right now is to notify Item listeners, no?

No, it is also used within the Thing framework to call the handlers on any command etc. So in general I would expect this code to be stable (note that it is identical to the thread pool management in UPnP, which also seems to work well).

**Comment by kgoderis** [comment] 2016-07-03 08:55
All these Timer threads are like this:

```
"Timer-7728" - Thread t@43977
   java.lang.Thread.State: WAITING
	at java.lang.Object.wait(Native Method)
	- waiting on <433c9d1d> (a java.util.TaskQueue)
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)

   Locked own able synchronisers
	- None:
```

**Comment by kaikreuzer** [comment] 2016-07-03 08:57
These are not threads of the thread pool. Any chance you can find out, who creates them? I doubt that they are from the ESH framework.

**Comment by kgoderis** [comment] 2016-07-03 08:58
> On the Executor, the only place it is used right now is to notify Item listeners, no?
> No, it is also used within the Thing framework to call the handlers on any command etc. So in general I would expect this code to be stable (note that it is identical to the thread pool management in UPnP, which also seems to work well).

I meant the ITEM_THREADPOOLNAME instance then. I am sure the code is stable, but it is the ITEM_THREADPOOLNAME that taking up the resources.

on the Timer threads : I  have some Lambda functions in my rules, and afaik are bug-free as they run stable since a long time on the old runtime. Should Timer explicitly be destroyed in Rules?

**Comment by kgoderis** [comment] 2016-07-03 08:59
> These are not threads of the thread pool. Any chance you can find out, who creates them? I doubt that they are from the ESH framework.

No, they are not from the pool, indeed. It just something I noticed after a day of profiling, and is an issue apart...

**Comment by kaikreuzer** [comment] 2016-07-03 09:06
> Should Timer explicitly be destroyed in Rules?

No, as long as you do not hold a reference to it anymore, it should be automatically removed by GC after it has been executed.

**Comment by kgoderis** [comment] 2016-07-04 17:43
@kaikreuzer Ok, here we have it : https://github.com/openhab/openhab2-addons/issues/358 
and seemingly https://github.com/openhab/openhab/pull/3275 never got merged!

**Comment by kaikreuzer** [comment] 2016-07-04 20:26
Ah, so you are chasing the same bug every half year again 😎 
Let's hope that it is indeed solved now - at least I am closing this issue as it seems to be pretty clear to be unrelated to the Karaf console.

**Closed by kaikreuzer** 2016-07-04 20:26 UTC

**Comment by kgoderis** [comment] 2016-07-05 07:12
The timer treads issue is in fact different, but If I experience the hick-ups again (without the rrd4j being active), I will re-open it
