### ISSUE TITLE
openHAB fails to start if addons.kar is used

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-distro#519] opened 2017-08-15 19:51 UTC
Seemingly since the Karaf upgrade from 4.0.8 to 4.1.2, the runtime fails to start if the addons.kar file is used (instead of having it download the addons from the remote repo).

On the first startup everything seems fine, but once the runtime is restarted for the first time, it starts failing. See details about the symptoms in https://github.com/openhab/openhab-distro/issues/518.

**Comment by lolodomo** [comment] 2017-08-24 15:37
Hi @kaikreuzer : any progress ?

**Comment by kaikreuzer** [comment] 2017-08-24 18:56
Not from my side (no time for it, sorry). But I have put a bounty on it, maybe it helps to find someone with Karaf experience to help on that matter...

**Comment by lolodomo** [comment] 2017-09-09 11:27
I tried snapshot 1034 without the kar file and it works as expected. So I will change my way to use OH and now rely on the ONLINE repo. Is it explained somewhere what are the consequence of using the ONLINE repo ? I would like to know if and when my bindings will be updated ?

**Comment by maggu2810** [comment] 2017-09-19 18:58
> But I have put a bounty on it, maybe it helps to find someone with Karaf experience to help on that matter...

I give it a try.
@kaikreuzer I assume I found a solution / workaround, but it depends on your requirements :wink: 

The checkout of all the openHAB repositories (currently openHAB 1 addons) seems to be pretty slow (at least here). If all is cloned I will test a local build with the changes in mind.

**Comment by kaikreuzer** [comment] 2017-11-28 06:46
I was able to track this issue down to an `removeRepository()` call of the [KarServiceImpl](https://github.com/apache/karaf/blob/karaf-4.1.3/kar/src/main/java/org/apache/karaf/kar/internal/KarServiceImpl.java#L270). Appearently, Felix FileInstall notices the KAR file on every startup and passes it on to the KarService, which then newly installs it - resulting in a full deinstallation of all our features first.

I cannot figure out what why this worked ok in the past and whether it is rather FileInstall or the KarService that has changed. @splatch Do you might have any clue on what is going on here and how we could avoid the unnecessary removal of the repo on startup?

**Comment by wborn** [comment] 2017-11-29 14:57
@kaikreuzer Is it also reproducible by installing KAR files via the console [KARAF-4310](https://issues.apache.org/jira/browse/KARAF-4310)?

**Comment by kaikreuzer** [comment] 2017-11-29 15:00
I don't think so as this would be a one-time installation. From my analysis above, the issue is that the KAR is re-added on every startup through the FileInstall bundle. KARAF-4310 is probably unrelated.

**Comment by splatch** [comment] 2017-12-03 00:06
@kaikreuzer Hey, thanks for pulling me in and analysis so far. FIleinstall is a simple component and always push things to karaf. For configuration files such XML - there is a new bundle generated which is then tracked. For configuration there is a config admin who manages state of configs, KAR files are handled differently than above two and have it's own deployment logic. I gonna check what goes on.

**Comment by kaikreuzer** [comment] 2017-12-03 22:16
Thanks for looking into it @splatch! Imho the important info is that it all works in openHAB 2.1 - so the mechanism shouldn't be fundamentally flawed, but something must have changed on the Karaf/FileInstall side...

**Comment by maggu2810** [comment] 2017-12-03 23:01
I assume it has been auto closed as you merged #538 and should be reopened.

**Comment by wborn** [comment] 2017-12-06 00:40
When the `KarArtifactInstaller` installs a KAR file it passes through some peculiar code. It [checks](https://github.com/apache/karaf/blob/a008cbfd31b6f997af0b5bfc65aa8cacd6c5eb2f/deployer/kar/src/main/java/org/apache/karaf/deployer/kar/KarArtifactInstaller.java#L43) if the KAR file is already installed but this check does not evaluate to true so it will always try to install the KAR:

```
        // check if the KAR is not already installed
        if (karService.list().contains(file.getName())) {
            LOGGER.info("KAR {} is already installed. Please uninstall it first.", file.getName());
            return;
        }
```

According to my debugger `karService.list()` always returns the names of the directories in `/userdata/kar` i.e. the same as you see on the console with:
```
openhab> kar:list
KAR Name
────────────────────────────────────
openhab-addons-2.2.0-SNAPSHOT
openhab-addons-legacy-2.2.0-SNAPSHOT
```
However `file.getName()` always returns the full name including the `.kar` extension, i.e.:
`openhab-addons-2.2.0-SNAPSHOT.kar`
`openhab-addons-legacy-2.2.0-SNAPSHOT.kar`

In openHAB 2.1.0 it is using exactly the same logic but for some reason the uninstall/install does not result in any issues. 

So I also checked what happend when I append `.kar` to the directories in `/userdata/kar` and it will then not try to reinstall the KAR files so it also does not result in any issues when restarting openHAB!

Maybe the check in KarArtifactInstaller should be rewritten to:

        if (karService.list().contains(getKarName(file))) {

If you look at the [history](https://github.com/apache/karaf/commit/e690f7b373a3356a23a4ccbfc48ed2b3f4de717f#diff-c87eb0f4094df60fd98baa9d7649935fR42) of the 1KarArtifactInstaller` there used to be some smarter logic in place (in 2011) that also checked if the KAR file was modified through `alreadyExtracted(..)`.

**Comment by splatch** [comment] 2017-12-06 01:04
It could be that felix file install which is responsible for handling of deploy folder changed something. This is pure guess at this moment, but if Karaf logic didn't change then it might be change in fileinstall as Karaf 4.0.8 uses version 3.5.6 while 4.1.3 is tied with 3.5.8.

**Comment by kaikreuzer** [comment] 2017-12-08 13:59
>  it might be change in fileinstall as Karaf 4.0.8 uses version 3.5.6 while 4.1.3 is tied with 3.5.8.

I have just replaced fileinstall 3.5.8 by 3.5.6 in my 2.2 distro and the behavior is the very same. So I am afraid we can rule out any change in fileinstall as well :-(

> In openHAB 2.1.0 it is using exactly the same logic but for some reason the uninstall/install does not result in any issues.

@wborn That is interesting! Does it mean that the comparison also resulted in false and uninstall is triggered in OH 2.1 as well? Why isn't it then executed...?

**Comment by wborn** [comment] 2017-12-08 22:57
@kaikreuzer  Apparently in OH 2.1 when the new repository is added the old repository is also removed including all features.

However while uninstalling the first feature an exception occurs so it will never really finish uninstalling features. The KarServiceImpl will also log this as warning, but by default OH 2.1 has raised the log level of the KarServiceImpl to ERROR. :open_mouth:

When lowering the log level you will see this warning:

```
23:43:54.389 [WARN ] [he.karaf.kar.internal.KarServiceImpl] - Unable to add repository 'mvn:org.openhab.distro/openhab-addons-legacy/2.1.0/xml/features'
java.lang.IllegalArgumentException: Feature named 'openhab-binding-astro1/1.10.0' is not installed
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.uninstallFeatures(FeaturesServiceImpl.java:997)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.uninstallFeatures(FeaturesServiceImpl.java:872)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.removeRepository(FeaturesServiceImpl.java:528)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.features.internal.service.FeaturesServiceImpl.removeRepository(FeaturesServiceImpl.java:491)[8:org.apache.karaf.features.core:4.0.8]
	at org.apache.karaf.kar.internal.KarServiceImpl.addToFeaturesRepositories(KarServiceImpl.java:259)[48:org.apache.karaf.kar.core:4.0.8]
	at org.apache.karaf.kar.internal.KarServiceImpl.install(KarServiceImpl.java:105)[48:org.apache.karaf.kar.core:4.0.8]
	at org.apache.karaf.kar.internal.KarServiceImpl.install(KarServiceImpl.java:94)[48:org.apache.karaf.kar.core:4.0.8]
	at org.apache.karaf.deployer.kar.KarArtifactInstaller.install(KarArtifactInstaller.java:50)[40:org.apache.karaf.deployer.kar:4.0.8]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:937)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.install(DirectoryWatcher.java:871)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:485)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361)[4:org.apache.felix.fileinstall:3.5.6]
	at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312)[4:org.apache.felix.fileinstall:3.5.6]
```

In Karaf 4.1.2 the repository and feature uninstallation logic has been reworked so the exception no longer occurs and the features now actually uninstalled.

But as I wrote in my previous comment I still think this behavior is actually wrong because of the KAR and repository mismatch.

**Comment by kaikreuzer** [comment] 2017-12-09 09:19
Thanks @wborn, great observations! I can only assume that I once raised the logging level to ERROR, because of that bug that resulted in annoying log entries.

So for fixing this issue, we should probably build ourselves a patched version of the KarServiceImpl, which correctly does the comparison against the file names, right? Is this something you could try?

**Comment by wborn** [comment] 2017-12-09 12:10
@kaikreuzer Using the reworked check in Karaf 4.1.3 seems to fix the issue for me. 

A full Karaf 4.1.3 release with this fix is available from https://github.com/wborn/karaf/releases/tag/karaf-4.1.3-issue-519.

It was build using:
* the code in the https://github.com/wborn/karaf/tree/karaf-4.1.3-issue-519 branch 
* Maven 3.3.9
* Java 1.8.0_151
* issuing the `mvn` command in the root, see also [BUILDING](https://github.com/wborn/karaf/blob/karaf-4.1.3-issue-519/BUILDING)

The change is part of [org.apache.karaf.deployer.kar-4.1.3.jar](https://github.com/wborn/karaf/releases/download/karaf-4.1.3-issue-519/org.apache.karaf.deployer.kar-4.1.3.jar) which you can use to replace the existing file in `/runtime/system/org/apache/karaf/deployer/org.apache.karaf.deployer.kar/4.1.3`

**Comment by wborn** [comment] 2017-12-09 15:43
> I can only assume that I once raised the logging level to ERROR, because of that bug that resulted in annoying log entries.

It seems to have been [always on ERROR](https://github.com/openhab/openhab-distro/pull/369/files#diff-1b11c2a039bbe1a722e3694b6811da7aR18) ever since KAR files were introduced with #369 . But that of course made perfect sense because functionally nothing was wrong.

The KarServiceImpl logger is [currently commented](https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/userdata/etc/org.ops4j.pax.logging.cfg#L61)  so I think it can be removed when all works well.

**Comment by wborn** [comment] 2017-12-09 16:28
Hmm, I think you never found the time to [file the issue](https://github.com/openhab/openhab-distro/pull/369#issuecomment-271319755) about uninstallation @kaikreuzer ? :wink:

**Comment by kaikreuzer** [comment] 2017-12-09 20:22
@wborn Excellent work, I tested it and it indeed solved the issue 🎉 

> The change is part of org.apache.karaf.deployer.kar-4.1.3.jar which you can use to replace the existing file in /runtime/system/org/apache/karaf/deployer/org.apache.karaf.deployer.kar/4.1.3

I wonder if it would be cleaner to create a 4.1.3-sp1 version of it to make it clear that it is a modified jar. We should be able to use the [override mechanism](https://github.com/openhab/openhab-distro/issues/573#issuecomment-346301629) to make Karaf use it, wdyt?

> The KarServiceImpl logger is currently commented so I think it can be removed when all works well.

Yes!

> I think you never found the time to file the issue about uninstallation @kaikreuzer ?

Looks like it. So might you be more successful now and file a bug at Karaf and directly provide a fix for it as well?

**Comment by wborn** [comment] 2017-12-09 20:40
> I tested it and it indeed solved the issue :tada:

Super!

> We should be able to use the override mechanism to make Karaf use it, wdyt?

It would be more clear indeed when that works out. So I'll update the versions in the POMs to 4.1.3-sp1 and see if it also results in a usable release. :-)

> So might you be more successful now and file a bug at Karaf and directly provide a fix for it as well?

Yes I'll create an upstream issue for this.

**Comment by kaikreuzer** [comment] 2017-12-09 20:52
The bounty is almost yours 🎉

**Comment by wborn** [comment] 2017-12-09 21:32
@kaikreuzer There is a 4.1.3-sp1 release now: https://github.com/wborn/karaf/releases/tag/karaf-4.1.3-sp1

**Comment by kaikreuzer** [comment] 2017-12-09 22:03
Cool! So can you create a PR against the distro to include that through the override mechanism?

**Comment by wborn** [comment] 2017-12-09 22:16
I'll have a look at that too. There's also a [KARAF-5533](https://issues.apache.org/jira/browse/KARAF-5533) issue for this now.

**Comment by splatch** [comment] 2017-12-09 22:53
Exceent work @weborn!🥂
Thanks for registering issue, as your fix works fine I will apply it in Karaf. Im not sure about exact schedule, as we have just a week and half left in December (I dont count time around Christmas) it might be difficult to get release over.
 
Overrides mechanism is workin at feature resolver level (swapping urls) so it should be able to pick up your KAR fixes easily. KAR handling is additional feature on top if core framework, despite of its use it for making assembly.

**Comment by wborn** [comment] 2017-12-09 23:28
> I will apply it in Karaf. 

That would be great @splatch! Almost everyone is finishing releases just before :christmas_tree:  :-)

**Comment by kaikreuzer** [comment] 2017-12-09 23:29
Yeah, but Karaf comes too late for openHAB 2.2, but it would indeed be very nice if we wouldn't have to reapply this fix once we move to Karaf 4.2.x next year.

**Closed** 2017-12-09 23:32 UTC
Labels: bounty, bug

**Comment by splatch** [comment] 2017-12-13 01:11
Just FYI - Karaf 4.1.x and 4.2.x have been patched with fix proposed by @wborn. Release vote of 4.1.4 is planned for this Friday. If it doesn't get delayed early next week 4.1.4 will be there early next week.

Cheers,
Lukasz

**Comment by kaikreuzer** [comment] 2017-12-13 06:43
Sounds great, thanks for the update!

**Comment by wborn** [comment] 2017-12-13 08:57
Thanks @splatch ! The unit test will also make sure this issue will hopefully never return.

I've also tested removal of the KAR file while OH is running. The repository and features are uninstalled but the [warnings](https://github.com/openhab/openhab-distro/pull/369#issuecomment-271318622) are still there. So perhaps we should also enter an issue for that.

**Comment by kaikreuzer** [comment] 2017-12-15 08:29
@wborn I just upgraded my production system to the latest build and after a restart, I see this (and many more errors) in the log:
```
09:26:50.197 [WARN ] [che.karaf.kar.internal.KarServiceImpl] - Unable to add repository 'mvn:org.openhab.distro/openhab-addons/2.2.0-SNAPSHOT/xml/features'
org.apache.karaf.features.internal.util.MultiException: Error restarting bundles:
      Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="0.10.0.b1"; osgi.identity="org.eclipse.smarthome.model.script.runtime"; singleton:="true" [id=147] STARTED [STARTED]
      at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:896) ~[?:?]
      at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1248) ~[?:?]
      at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$1(FeaturesServiceImpl.java:1147) ~[?:?]
      at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
      at java.lang.Thread.run(Thread.java:745) [?:?]
      Suppressed: org.osgi.framework.BundleException: Unable to acquire the state change lock for the module: osgi.identity; type="osgi.bundle"; version:Version="0.10.0.b1"; osgi.identity="org.eclipse.smarthome.model.script.runtime"; singleton:="true" [id=147] STARTED [STARTED]
        at org.eclipse.osgi.container.Module.lockStateChange(Module.java:337) ~[?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:401) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.startBundle(FeaturesServiceImpl.java:1361) ~[?:?]
        at org.apache.karaf.features.internal.service.Deployer.deploy(Deployer.java:888) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.doProvision(FeaturesServiceImpl.java:1248) ~[?:?]
        at org.apache.karaf.features.internal.service.FeaturesServiceImpl.lambda$doProvisionInThread$1(FeaturesServiceImpl.java:1147) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:?]
        at java.lang.Thread.run(Thread.java:745) [?:?]
      Caused by: java.util.concurrent.TimeoutException: Timeout after waiting 5 seconds to acquire the lock.
        at org.eclipse.osgi.container.Module.lockStateChange(Module.java:334) ~[?:?]
        ... 11 more
```
That slightly worries me 2 days before the release - any idea, what that could mean?

**Comment by kaikreuzer** [comment] 2017-12-15 09:16
It does not seem to have any functional impact though - my system comes up as expected.
I've therefore created https://github.com/openhab/openhab-distro/pull/611 to filter those log entries.

**Comment by wborn** [comment] 2017-12-16 21:13
@kaikreuzer For all we know the warning may have always been there but been suppressed because KarServiceImpl was previously also on ERROR.  Maybe the `TimeoutException: Timeout after waiting 5 seconds to acquire the lock.` occurs because your production system is a bit more resource constrained?
